config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :students
  resources :courses
  resources :classrooms, only: [:new, :create]
  resources :home, only: :index
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base

  # associations

  belongs_to :student, inverse_of: :classrooms
  belongs_to :course, inverse_of: :classrooms

  # validations

  validates :entry_at, presence: true
  validates :student, presence: true
  validates :course, presence: true
  validates :student_id, uniqueness: { scope: :course_id }

end

app/models/course.rb
class Course < ActiveRecord::Base

  # enums

  has_enumeration_for :status, create_helpers: true

  # associations

  has_many :classrooms,
           inverse_of: :course,
           dependent: :destroy

  has_many :students, through: :classrooms

  # validations

  validates :name, presence: true
  validates :description, presence: true
  validates :status, presence: true

end

app/models/student.rb
class Student < ActiveRecord::Base

  # enums

  has_enumeration_for :status, create_helpers: true

  # associations

  has_many :classrooms,
           inverse_of: :student,
           dependent: :destroy

  has_many :courses, through: :classrooms

  # validations

  validates :name, presence: true
  validates :register_number, presence: true, uniqueness: true
  validates :status, presence: true

end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController

  # constants

  PERMITTED_PARAMS = [
    :student_id,
    :course_id,
    :entry_at
  ]

  # exposures

  expose :classroom, attributes: :classroom_params

  def index
    redirect_to new_classroom_path
  end

  def new
  end

  def create
    if classroom.save
      flash[:notice] = t('flash.actions.create.notice', resource_name: t('classroom'))
    end
    respond_with classroom, location: -> { courses_path }
  end

  # private methods

  private

  def classroom_params
    params.require(:classroom).permit(PERMITTED_PARAMS)
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  # constants

  PERMITTED_PARAMS = [
    :name,
    :description,
    :status
  ]

  # exposures

  expose(:courses) { all_courses }
  expose :course, attributes: :course_params

  # actions

  def index
  end

  def new
  end

  def create
    flash[:notice] = t('flash.actions.create.notice', resource_name: course.name) if course.save
    respond_with course, location: -> { courses_path }
  end

  def edit
  end

  def update
    if course.update(course_params)
      flash[:notice] = t('flash.actions.update.notice', resource_name: course.name)
    end
    respond_with course
  end

  def destroy
    if course.destroy
      flash[:notice] = t('flash.actions.destroy.notice', resource_name: course.name)
    end
    respond_with course, location: -> { courses_path }
  end

  # private methods

  private

  def course_params
    params.require(:course).permit(PERMITTED_PARAMS)
  end

  def all_courses
    Course.all
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # actions

  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  # constants

  PERMITTED_PARAMS = [
    :name,
    :register_number,
    :status
  ]

  # exposures

  expose(:students) { all_students }
  expose :student, attributes: :student_params

  # actions

  def index
  end

  def new
  end

  def create
    flash[:notice] = t('flash.actions.create.notice', resource_name: student.name) if student.save
    respond_with student, location: -> { students_path }
  end

  def show
  end

  def edit
  end

  def update
    if student.update(student_params)
      flash[:notice] = t('flash.actions.update.notice', resource_name: student.name)
    end
    respond_with student
  end

  def destroy
    if student.destroy
      flash[:notice] = t('flash.actions.destroy.notice', resource_name: student.name)
    end
    respond_with student, location: -> { students_path }
  end

  # private methods

  private

  def student_params
    params.require(:student).permit(PERMITTED_PARAMS)
  end

  def all_students
    Student.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
  def students_map
    Student.all.map { |s| [s.name, s.id] }
  end

  def courses_map
    Course.all.map { |c| [c.name, c.id] }
  end
end

app/views/classrooms/_form.html.slim
- if flash[:notice]
  .alert.alert-danger = flash[:notice]

- if flash[:alert]
  .alert.alert-danger = flash[:alert]

= form_for classroom do |f|
  fieldset.form-group
    = f.label :student
    = f.select :student_id, students_map, {}, { class: 'form-control' }
  fieldset.form-group
    = f.label :course
    = f.select :course_id, courses_map, {}, { class: 'form-control' }
  fieldset.form-group
    = f.hidden_field :entry_at, value: DateTime.now
    = f.submit t('save'), class: 'btn btn-primary pull-right'

app/views/classrooms/edit.html.slim
h1
  = t('.edit_classroom')

= render 'form'

app/views/classrooms/new.html.slim
h1
  = t('.new_classroom')

= render 'form'

app/views/courses/_form.html.slim
- if flash[:alert]
  .alert.alert-danger = flash[:alert]

= form_for course do |f|
  fieldset.form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  fieldset.form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  fieldset.form-group
    = f.label :status
    = f.select :status, Status.to_a, {}, { class: 'form-control' }
  fieldset.form-group
    = f.submit t('save'), class: 'btn btn-primary pull-right'

app/views/courses/edit.html.slim
h1
  = t('.edit_course')

= render 'form'

app/views/courses/index.html.slim
- if flash[:notice]
  .alert.alert-success = flash[:notice]

- if flash[:alert]
  .alert.alert-danger = flash[:alert]


= link_to t('add'), new_course_path, class: 'btn btn-primary pull-right'

h1
  = t('.courses')

.row
  .col-xs-12
    .table-responsive
      table.table
        table.table
          thead
            tr
              th
                = Course.human_attribute_name(:name)
              th
                = t('actions')
          tbody
            - courses.each do |course|
                tr
                  td
                    = link_to course.name, course_path(course)
                  td
                    = link_to edit_course_path(course), class: "btn btn-success btn-xs" do
                      span.glyphicon.glyphicon-pencil
                    = link_to course_path(course),
                      data: { confirm: t('remove_register_confirmation') },
                      method: :delete, class: "btn btn-danger btn-xs" do
                      span.glyphicon.glyphicon-trash

app/views/courses/new.html.slim
h1
  = t('.new_course')

= render 'form'

app/views/courses/show.html.slim
- students = course.students

- if flash[:notice]
  .alert.alert-success = flash[:notice]

h1
  = course.name

.row
  .col-xs-12
    p
      = Course.human_attribute_name(:description)
.row
  .col-xs-12
    = course.description

.row
  .col-xs-2
    = Course.human_attribute_name(:status)
  .col-xs-2
    = course.status_humanize

- if students.present?
  h3
    = t('.students')

  .row
    - students.each do |student|
      .col-xs-4
        .card-block
          h4.card-title = student.name
          = link_to t('show'), student_path(student), class: 'btn btn-primary'

app/views/home/index.html.slim
h1
  = t('.home')

.row
  .col-xs-4
    .card-block
      h4.card-title = t('.students')
      p.card-text Some quick example text to build on the card title and make up the bulk of the card's content.
      = link_to t('.students'), students_path, class: 'btn btn-primary'

  .col-xs-4
    .card-block
      h4.card-title = t('.courses')
      p.card-text Some quick example text to build on the card title and make up the bulk of the card's content.
      = link_to t('.courses'), courses_path, class: 'btn btn-primary'

  .col-xs-4
    .card-block
      h4.card-title = t('.add_classroom')
      p.card-text Some quick example text to build on the card title and make up the bulk of the card's content.
      = link_to t('.add_classroom'), new_classroom_path, class: 'btn btn-primary'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Sistema de Gestão de Cursos
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container
      nav.navbar.navbar-inverse.navbar-fixed-top.m-b-2
        .navbar-header
          button.navbar-toggle data-target="#system-navbar" data-toggle="collapse" type="button"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'Sistema de Gestão de Cursos', root_path, class: 'navbar-brand'

        #system-navbar.collapse.navbar-collapse
          ul.nav.navbar-nav
            li
              = link_to Student.model_name.human, students_path
            li
              = link_to Course.model_name.human, courses_path
            li
              = link_to Classroom.model_name.human, new_classroom_path

      = yield

app/views/students/_form.html.slim
- if flash[:alert]
  .alert.alert-danger = flash[:alert]

= form_for student do |f|
  fieldset.form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  fieldset.form-group
    = f.label :register_number
    = f.text_field :register_number, class: 'form-control'
  fieldset.form-group
    = f.label :status
    = f.select :status, Status.to_a, {}, { class: 'form-control' }
  fieldset.form-group
    = f.submit t('save'), class: 'btn btn-primary pull-right'

app/views/students/edit.html.slim
h1
  = t('.edit_student')

= render 'form'

app/views/students/index.html.slim
- if flash[:notice]
  .alert.alert-success = flash[:notice]

- if flash[:alert]
  .alert.alert-danger = flash[:alert]

.row
  = link_to t('add'), new_student_path, class: 'btn btn-primary pull-right'

h1
  = t('.students')

.row
  .col-xs-12
    .table-responsive
      table.table
        table.table
          thead
            tr
              th
                = Student.human_attribute_name(:name)
              th
                = t('actions')
          tbody
            - students.each do |student|
                tr
                  td
                    = link_to student.name, student_path(student)
                  td
                    = link_to edit_student_path(student), class: "btn btn-success btn-xs" do
                      span.glyphicon.glyphicon-pencil
                    = link_to student_path(student), data: { confirm: t('remove_register_confirmation') }, method: :delete, class: "btn btn-danger btn-xs" do
                      span.glyphicon.glyphicon-trash

app/views/students/new.html.slim
h1
  = t('.new_student')

= render 'form'

app/views/students/show.html.slim
- courses = student.courses

- if flash[:notice]
  .alert.alert-success = flash[:notice]

h1
  = student.name

.row
  .col-xs-2
    = Student.human_attribute_name(:register_number)
  .col-xs-2
    = student.register_number

.row
  .col-xs-2
    = Student.human_attribute_name(:status)
  .col-xs-2
    = student.status_humanize

- if courses.present?
  h3
    = t('.courses')

  .row
    - courses.each do |course|
      .col-xs-4
        .card-block
          h4.card-title = course.name
          = link_to t('show'), course_path(course), class: 'btn btn-primary'